services:

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'if [ ! -f /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem ]; then certbot certonly --standalone --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_NAME} -d www.${DOMAIN_NAME}; fi; trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL: ${EMAIL}

  nginx:
    build: .
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/www:/var/www/html
    ports:
      - "7890:7890"
    command: /usr/bin/goaccess /var/log/nginx/access.log --log-format=COMBINED --real-time-html -o /var/www/html/report.html
    depends_on:
      - nginx
